name: mzizichurchsystem
description: Mzizi Church Mobile App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  line_icons: ^0.2.0
  carousel_slider: ^2.0.0
  youtube_player_flutter: ^6.1.1
  webview_media: ^0.1.2
  font_awesome_flutter: ^8.8.1
  ##Online

  dio: ^2.1.13
  #intl: ^0.16.0
  #Because flutter_money_formatter >=0.8.2 depends on intl ^0.15.8
  #flutter_money_formatter: ^0.8.3
  pull_to_refresh: ^1.4.5
  flutter_selectable_text: ^0.3.1
  bubble:
  charts_flutter:
  fluttertoast: ^7.0.1+1
  progress_dialog: ^1.2.0
  groovin_widgets: ^1.4.2
  #http: ^0.12.0+1
  json_annotation:
  floor: ^0.9.0
  enhanced_future_builder: ^1.0.2
  json_serializable: ^2.3.0
  retrofit:
  logger:  #for logging purpose
  flutter_speed_dial: ^1.2.5
  shared_preferences: ^0.4.3
  url_launcher: ^5.2.5
  path_provider: ^1.3.0
  intl: ^0.15.7
  #intl: ^0.16.0
  flutter_money_formatter: ^0.8.3
  dropdownfield: 0.0.2
  google_fonts: ^0.3.5
  transparent_image: ^1.0.0
  add_thumbnail: ^0.0.2
  #money2: ^1.4.3
  #https://pub.dev/packages/cached_network_image/install
  cached_network_image: ^2.2.0+1
  get:
  sweetalert: ^0.0.1
  flutter_phoenix: ^0.1.0
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_datetime_picker: ^1.4.0
  http: ^0.12.2

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^0.9.0
  retrofit_generator:
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/member_app_assets/jcc_logo.png
   - assets/images/member_app_assets/jcc_logo2.png
   - assets/images/member_app_assets/dashboard_home_bg.jpg
   - assets/images/member_app_assets/megaphone.png
   - assets/images/member_app_assets/Curve-Loading.gif
   - assets/images/member_app_assets/photo_gallery.png
   - assets/images/member_app_assets/church.png
   - assets/images/member_app_assets/church_logo_no_bg2.png
   - assets/images/member_app_assets/church_logo.jpeg 
   - assets/images/member_app_assets/mzizi_church_logo.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
